### ISSUE TITLE
As a ruby developer I want to know what's happening in the ecosystem so I can stay up to date.

### ISSUE THREAD

**Issue by cwest** [mcw0933/kimono_rss#4]
Subscribe to and listen/read back episodes of [Ruby 5](https://ruby5.codeschool.com/).

Reddit's [ruby](http://www.reddit.com/r/ruby) and [rails](http://www.reddit.com/r/rails) subreddit's are actually good.

[Ruby Toolbox](https://www.ruby-toolbox.com/) is a decent tool for keeping up to date with gems.

**Comment by mcw0933** [comment]
Subscribed, thanks!
